encyclopedia/urls.py
from django.urls import path

from . import views

# app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create_page", views.create_page, name="create_page"),
    path("edit_page/<str:title>", views.edit_page, name="edit_page"),
    path("random_page", views.random_page, name="random_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("encyclopedia.urls", "encyclopedia"), namespace = "encyclopedia"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class NewPageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.read_only_title = kwargs.pop('read_only_title', False)
        super(NewPageForm, self).__init__(*args, **kwargs)
        if self.read_only_title:
            self.fields['title'].widget.attrs['readonly'] = True
            
    title = forms.CharField(label="Page title", max_length=100)
    content = forms.CharField(widget=forms.Textarea, label="Page content")

encyclopedia/views.py
from django.shortcuts import render, redirect
from .forms import NewPageForm
from . import util
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    page_content = util.get_entry(title)
    if page_content is None:
        return render(request, "encyclopedia/error.html", {
            "title": title + " not found",
            "message": "The requested page was not found."
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": page_content
        })
    
def search(request):
    query_str = request.GET.get('q')
    entries = util.list_entries()
    if query_str in entries:
        return redirect('encyclopedia:entry', title=query_str)
    else:
        # find those entries that contain the query string as a substring
        results = [entr for entr in entries if query_str.lower() in entr.lower()]
        return render(request, "encyclopedia/search.html", {
            "results": results,
            "query": query_str
        })

def create_page(request):
    if request.method == 'POST':
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            if util.get_entry(title) is not None:
                return render(request, "encyclopedia/error.html", {
                    "title": title,
                    'message': 'An wiki page with this title already exists.'
                })
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return redirect('encyclopedia:entry', title=title)
    else:
        return render(request, "encyclopedia/create_page.html", {
            "form": NewPageForm()
        })
    
def edit_page(request, title):
    if request.method == 'POST':
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return redirect('encyclopedia:entry', title=title)
    else:
        return render(request, "encyclopedia/edit_page.html", {
            "title": title,
            "form": NewPageForm(initial={'title': title, 'content': util.get_entry(title)}, read_only_title=True),
        })
    
def random_page(request):
    entries = util.list_entries()
    return redirect('encyclopedia:entry', title=random.choice(entries))

encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a new wikipedia page
{% endblock %}

{% block body %}
    <h1>Create your own wikipedia page!</h1>

    <form action="{% url 'encyclopedia:create_page' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
{% endblock %}

{% block body %}
    <h1>Edit page</h1>

    <form action="{% url 'encyclopedia:edit_page' title %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia: {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    {{ content }}

    <form action="{% url 'encyclopedia:edit_page' title %}" method="get">
        <button type="submit">Edit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ message }}</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia: Search Results
{% endblock %}

{% block body %}
    <h1>Your queried string: {{ query }}</h1>

    <ul>
        {% for result in results %}
            <li><a href="{% url 'encyclopedia:entry' result %}">{{ result }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}